// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prn231Flower.Data.Models;

public partial class Flower
{
    public int Id { get; set; }

    public int? UserId { get; set; }

    public string Type { get; set; }

    public int? Quantity { get; set; }

    public decimal? Price { get; set; }

    public int? Status { get; set; }

    public string Description { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string ImgUrl { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual User User { get; set; }
}