// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace prn231Flower.Data.Models;

public partial class OrderDetail
{
    public int Id { get; set; }

    public int? OrderId { get; set; }

    public int? FlowerId { get; set; }

    public int? Quantity { get; set; }

    public string Description { get; set; }

    public decimal? TotalPrice { get; set; }

    [JsonIgnore]
    public virtual Flower Flower { get; set; }

    [JsonIgnore]
    public virtual Order Order { get; set; }
}