// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace prn231Flower.Data.Models;

public partial class Payment
{
    public int Id { get; set; }

    public int? OrderId { get; set; }

    public string Method { get; set; }

    public string Status { get; set; }

    public decimal? Amount { get; set; }

    public DateTime? Date { get; set; }

    public virtual Order Order { get; set; }
}